<a href="https://colab.research.google.com/github/sarthakshrestha/learning-pytorch/blob/main/PyTorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals 00

In [ ]:
!nvidia-smi

Sun Feb 25 16:22:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


Tensors are building blocks of Machine Learning. It is a way of representing multi dimensional data

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Vector
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[2,3],
                       [4,5]])
matrix


tensor([[2, 3],
        [4, 5]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([4, 5])

In [ ]:
matrix[0]

tensor([2, 3])

In [ ]:
matrix.shape

torch.Size([2, 2])

# Tensor

In [ ]:
tensor = torch.tensor([[[1,2,3],[4,5,6], [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])